enum DomainTag {
    /*0*/ START,
    /*1*/ WHITESPACE,
    /*2*/ IDENT_1,
    /*3*/ IDENT_2,
    /*4*/ IDENT,
    /*5*/ KEYWORD,
    /*6*/ NUM_LITER,
    /*7*/ PREOP_1,
    /*8*/ PREOP_2,
    /*9*/ OP,
    /*10*/ STR_START,
    /*11*/ STR_LITERAL,
    /*12*/ ERROR,
}